# Configuração de Conexão com o Banco de Dados (Prioriza as Variáveis de Ambiente do Railway)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:web2_db}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:06PeriardPedro!}

server.port=${PORT:8080}
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true